=== dertom95/dtTools/sample/urho.net/UrhoDotNet.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://UrhoDotNet.com" xmlns="https://UrhoDotNet.com" elementFormDefault="qualified">
	<xs:simpleType name="ctype" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bool"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="scharPtr"/>
			<xs:enumeration value="short"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="uint"/>
			<xs:enumeration value="void"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="root">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="main">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="class">
								<xs:complexType>
									<xs:choice minOccurs="0" maxOccurs="unbounded">
										<xs:element name="method">
											<xs:complexType>
												<xs:choice minOccurs="0" maxOccurs="unbounded">
													<xs:element name="params">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required"/>
															<xs:attribute name="type" type="ctype" use="required"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="rip">
														<xs:complexType>
															<xs:attribute name="rip" type="ctype"/>
														</xs:complexType>
													</xs:element>
												</xs:choice>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="returnType" type="ctype"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="rip">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="rip">
								<xs:complexType>
									<xs:attribute name="type" type="ctype"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dertom95/dtTools/sample/urho.net/gen-data.xml
<?xml version="1.0"?>

<root xmlns="https://UrhoDotNet.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://UrhoDotNet.com UrhoDotNet.xsd">
    <main>
        <class name="SoundStream">
            <method name="Seek" returnType="int">
                <params name="sample_number" type="uint" />
            </method>

            <method name="GetData" returnType="uint">
                <params name="dest" type="scharPtr" />
                <params name="numBytes" type="uint" />
            </method>
            <method name="SetFormat">
                <params name="frequency" type="uint" />
                <params name="sixteenBit" type="bool" />
                <params name="stereo" type="bool" />
            </method>
            <method name="SetStopAtEnd">
                <params name="enable" type="bool" />
            </method>
            <method name="GetSampleSize" returnType="uint">
            </method>
        </class>

        <class name="Mixi">
            <method name="KickIt2">
                <params name="hard2" type="bool" />
            </method>

            <method name="Execute2">
                <params name="filename2" type="string" />
                <params name="handle" type="int" />
            </method>
        </class>
    </main>

</root>
