=== dertom95/dtTools/sample/note.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<xs:element name="dotnet">  
    <xs:complexType>
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:attribute name="orderid" type="xs:string" use="required"/>                
                </xs:complexType>
            </xs:element>
            <xs:element name="intValue" type="xs:int"/>
            <xs:element name="note" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="to" type="xs:string" default="red"/>
                    <xs:element name="from" type="xs:string"/>
                    <xs:element name="heading" type="xs:string"/>
                    <xs:element name="body" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="note2" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="to2" type="xs:string" default="red"/>
                    <xs:element name="from2" type="xs:string"/>
                    <xs:element name="heading2" type="xs:string"/>
                    <xs:element name="body2" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>            
        </xs:sequence>
    </xs:complexType>

      
</xs:element>

</xs:schema>

=== dertom95/dtTools/sample/test.xml
<?xml version="1.0"?>

<dotnet xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com note.xsd">

<name orderid="1">Urho3DNodeTreeExporter</name>
<intValue>1</intValue>

<note>
   <to></to> 
   <from></from>
   <heading></heading>
   <body></body>
</note>

<!-- <note2>
    <to2></to2>
    <from2></from2>
    <heading2></heading2>
    <body2></body2>
</note2> -->

</notes>
